"""initial_backfill_schema

Revision ID: 4c37bc640970
Revises: 
Create Date: 2026-05-19 11:43:55.019404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4c37bc640970'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfill_agent_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('minimum_cancellation_notice_hours', sa.Integer(), nullable=False),
    sa.Column('sms_batch_size_per_wave', sa.Integer(), nullable=False),
    sa.Column('delay_between_waves_minutes', sa.Integer(), nullable=False),
    sa.Column('max_waves', sa.Integer(), nullable=False),
    sa.Column('ai_call_escalation_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_call_quantity_per_wave', sa.Integer(), nullable=False),
    sa.Column('allowed_contact_days', sa.String(length=32), nullable=False),
    sa.Column('contact_window_start', sa.Time(), nullable=False),
    sa.Column('contact_window_end', sa.Time(), nullable=False),
    sa.Column('contact_window_timezone', sa.String(length=64), nullable=False),
    sa.Column('use_shared_holiday_calendar', sa.Boolean(), nullable=False),
    sa.Column('agent_blackout_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('same_facility_required', sa.Boolean(), nullable=False),
    sa.Column('same_cpt_required', sa.Boolean(), nullable=False),
    sa.Column('exclude_no_show_enabled', sa.Boolean(), nullable=False),
    sa.Column('campaign_timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('late_response_closeout_enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_sms_template_id', sa.Integer(), nullable=True),
    sa.Column('allowed_voice_template_id', sa.Integer(), nullable=True),
    sa.Column('closeout_message_template_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('sms_opt_out', sa.Boolean(), nullable=False),
    sa.Column('no_show_flag', sa.Boolean(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_facility_cpt_status', 'appointments', ['facility_id', 'cpt_code', 'status'], unique=False)
    op.create_index('ix_appointments_scheduled_start', 'appointments', ['scheduled_start_at'], unique=False)
    op.create_table('backfill_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_type', sa.String(length=64), nullable=False),
    sa.Column('cancelled_appointment_id', sa.Integer(), nullable=False),
    sa.Column('cancelled_patient_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=32), nullable=False),
    sa.Column('open_slot_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancellation_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_notice_hours_applied', sa.Integer(), nullable=False),
    sa.Column('campaign_status', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_by_patient_id', sa.Integer(), nullable=True),
    sa.Column('filled_by_appointment_id', sa.Integer(), nullable=True),
    sa.Column('closed_reason', sa.String(length=255), nullable=True),
    sa.Column('created_by_system_flag', sa.Boolean(), nullable=False),
    sa.Column('last_wave_number', sa.Integer(), nullable=True),
    sa.Column('last_wave_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['cancelled_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['filled_by_appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['filled_by_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cancelled_appointment_id', name='uq_campaign_cancelled_appointment')
    )
    op.create_index('ix_backfill_campaigns_started_at', 'backfill_campaigns', ['started_at'], unique=False)
    op.create_index('ix_backfill_campaigns_status', 'backfill_campaigns', ['campaign_status'], unique=False)
    op.create_table('backfill_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backfill_campaign_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=32), nullable=False),
    sa.Column('scheduled_appointment_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rank_order', sa.Integer(), nullable=False),
    sa.Column('eligibility_status', sa.String(length=64), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=True),
    sa.Column('wave_number_first_contacted', sa.Integer(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_contact_status', sa.String(length=64), nullable=True),
    sa.Column('interested_flag', sa.Boolean(), nullable=True),
    sa.Column('declined_flag', sa.Boolean(), nullable=True),
    sa.Column('no_response_flag', sa.Boolean(), nullable=True),
    sa.Column('won_slot_flag', sa.Boolean(), nullable=True),
    sa.Column('lost_slot_flag', sa.Boolean(), nullable=True),
    sa.Column('response_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['backfill_campaign_id'], ['backfill_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backfill_campaign_id', 'appointment_id', name='uq_candidate_campaign_appointment')
    )
    op.create_index('ix_backfill_candidates_campaign_rank', 'backfill_candidates', ['backfill_campaign_id', 'rank_order'], unique=False)
    op.create_table('backfill_action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backfill_campaign_id', sa.Integer(), nullable=False),
    sa.Column('backfill_candidate_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('transcript_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('agent_run_id', sa.String(length=128), nullable=True),
    sa.Column('raw_response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wave_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['backfill_campaign_id'], ['backfill_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['backfill_candidate_id'], ['backfill_candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backfill_action_logs_campaign_at', 'backfill_action_logs', ['backfill_campaign_id', 'attempted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backfill_action_logs_campaign_at', table_name='backfill_action_logs')
    op.drop_table('backfill_action_logs')
    op.drop_index('ix_backfill_candidates_campaign_rank', table_name='backfill_candidates')
    op.drop_table('backfill_candidates')
    op.drop_index('ix_backfill_campaigns_status', table_name='backfill_campaigns')
    op.drop_index('ix_backfill_campaigns_started_at', table_name='backfill_campaigns')
    op.drop_table('backfill_campaigns')
    op.drop_index('ix_appointments_scheduled_start', table_name='appointments')
    op.drop_index('ix_appointments_facility_cpt_status', table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('patients')
    op.drop_table('facilities')
    op.drop_table('backfill_agent_settings')
    # ### end Alembic commands ###
